---
- name: install common packages
  become: yes
  hosts: all
  gather_facts: yes
  roles:
    - common
- name: install webserver
  become: yes
  hosts: webservers
  gather_facts: no
  roles:
    - webserver  
