---
# tasks file for role/nginx-role
- name: update cache
  apt:
    update_cache: yes

- name: install nginx
  apt:
    name: nginx
    state: present

- name: Deploy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'
    owner: root
    group: root
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

